"""add repository workspace and commit sha

Revision ID: 7a1b60b4ac51
Revises: 96df5295f2cb
Create Date: 2026-08-29 20:40:09.548298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a1b60b4ac51'
down_revision: Union[str, Sequence[str], None] = '96df5295f2cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('workspace_path', sa.Text(), nullable=True))
    op.add_column('repositories', sa.Column('latest_commit_sha', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'latest_commit_sha')
    op.drop_column('repositories', 'workspace_path')
    # ### end Alembic commands ###
