"""add repository workspace and commit sha

Revision ID: 91d7a384a2b2
Revises: 7a1b60b4ac51
Create Date: 2026-08-29 20:45:43.161075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91d7a384a2b2'
down_revision: Union[str, Sequence[str], None] = '7a1b60b4ac51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
