"""add overall score to analysis runs

Revision ID: e17da25efa3a
Revises: 076a2b0d5d54
Create Date: 2026-09-01 23:32:11.729707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e17da25efa3a'
down_revision: Union[str, Sequence[str], None] = '076a2b0d5d54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_runs', sa.Column('overall_score', sa.Float(), nullable=True))
    op.add_column('analysis_runs', sa.Column('category_scores', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_runs', 'category_scores')
    op.drop_column('analysis_runs', 'overall_score')
    # ### end Alembic commands ###
