
from uuid import UUID
from app.models.finding import Finding
from app.schemas.finding import FindingResponse
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from app.db.database import get_db
from app.schemas.agent_trajectory import AgentTrajectoryResponse
from app.services.agent_trajectory_service import list_trajectory_steps

from app.schemas.analysis import (
    AnalysisCreate,
    AnalysisResponse,
)
from app.services.analysis_service import (
    AnalysisError,
    create_analysis,
    execute_analysis,
    get_analysis,
     list_analyses,
)

router = APIRouter(
    prefix="/analyses",
    tags=["Analyses"],
)

@router.get(
    "/{analysis_id}/trajectory",
    response_model=list[AgentTrajectoryResponse],
)
def get_analysis_trajectory(
    analysis_id: UUID,
    db: Session = Depends(get_db),
):
    """
    Get the agent execution trajectory for an analysis run.
    """

    return list_trajectory_steps(
        db=db,
        analysis_run_id=analysis_id,
    )

@router.post(
    "",
    response_model=AnalysisResponse,
    status_code=201,
)
def create_analysis_route(
    payload: AnalysisCreate,
    db: Session = Depends(get_db),
):
    """
    Create a new analysis run for a repository.
    """

    try:
        analysis = create_analysis(
            db=db,
            repository_id=payload.repository_id,
            agent_type=payload.agent_type,
        )

        return analysis

    except AnalysisError as exc:
        raise HTTPException(
            status_code=404,
            detail=str(exc),
        ) from exc

    except Exception as exc:
        raise HTTPException(
            status_code=500,
            detail=f"Analysis creation failed: {exc}",
        ) from exc


@router.post(
    "/{analysis_id}/run",
    response_model=AnalysisResponse,
)
def run_analysis_route(
    analysis_id: UUID,
    db: Session = Depends(get_db),
):
    """
    Execute a queued analysis.
    """

    try:
        analysis = execute_analysis(
            db=db,
            analysis_id=analysis_id,
        )

        return analysis

    except AnalysisError as exc:
        raise HTTPException(
            status_code=400,
            detail=str(exc),
        ) from exc

    except Exception as exc:
        raise HTTPException(
            status_code=500,
            detail=f"Analysis execution failed: {exc}",
        ) from exc




@router.get(
    "",
    response_model=list[AnalysisResponse],
)
def list_analyses_route(
    db: Session = Depends(get_db),
):
    """
    Get all analysis runs.
    """

    return list_analyses(db=db)
@router.get(
    "/{analysis_id}",
    response_model=AnalysisResponse,
)
def get_analysis_route(
    analysis_id: UUID,
    db: Session = Depends(get_db),
):
    """
    Get an analysis run by ID.
    """

    analysis = get_analysis(
        db=db,
        analysis_id=analysis_id,
    )

    if not analysis:
        raise HTTPException(
            status_code=404,
            detail="Analysis not found",
        )

    return analysis

@router.get(
    "/{analysis_id}/findings",
    response_model=list[FindingResponse],
)
def get_analysis_findings(
    analysis_id: UUID,
    db: Session = Depends(get_db),
):
    """
    Get all findings generated by an analysis run.
    """

    analysis = get_analysis(
        db=db,
        analysis_id=analysis_id,
    )

    if not analysis:
        raise HTTPException(
            status_code=404,
            detail="Analysis not found",
        )

    findings = (
        db.query(Finding)
        .filter(
            Finding.analysis_run_id == analysis_id
        )
        .order_by(
            Finding.created_at.asc()
        )
        .all()
    )

    return findings